version: '3'
services:
 db:
   image: mariadb
   environment:
    - MARIADB_ROOT_PASSWORD=1234
   ports:
    - "3306:3306"
 web:
  build:
   context: .
   dockerfile: ./compose/springboot/Dockerfile
  ports:
   - "8080:8080"
  volumes:
   - ./:/app/