names = ['moo_mium_1','moo_mium_2','moo_mium_3','moo_mium_4',
        'moo_woo_1','moo_woo_2','moo_woo_3','moo_woo_4',
        'goong_giuk_1', 'goong_giuk_2', 'goong_giuk_3',
        'goong_woo_1','goong_woo_2','goong_woo_3', 'goong_woo_4',
        'goong_ieung_1','goong_ieung_2','goong_ieung_3','goong_ieung_4',
        'hwa_hieut_1', 'hwa_hieut_2', 'hwa_hieut_3', 'hwa_hieut_4', 'hwa_hieut_5', 'hwa_hieut_6', 'hwa_hieut_7', 'hwa_hieut_8',
        'hwa_oh_1', 'hwa_oh_2', 'hwa_oh_3', 'hwa_oh_4',
        'hwa_ah_1', 'hwa_ah_2', 'hwa_ah_3', 'hwa_ah_4',
        'ggot_ggiuk_1', 'ggot_ggiuk_2', 'ggot_ggiuk_3', 'ggot_ggiuk_4', 'ggot_ggiuk_5', 'ggot_ggiuk_6',
        'ggot_oh_1', 'ggot_oh_2', 'ggot_oh_3', 'ggot_oh_4',
        'ggot_chieut_1', 'ggot_chieut_2', 'ggot_chieut_3', 'ggot_chieut_4', 'ggot_chieut_5', 'ggot_chieut_6', 'ggot_chieut_7', 'ggot_chieut_8',
        'lee_ieung_1', 'lee_ieung_2', 'lee_ieung_3', 'lee_ieung_4',
        'lee_lee_1', 'lee_lee_2',
        'pee_pieub_1', 'pee_pieub_2', 'pee_pieub_3', 'pee_pieub_4', 'pee_pieub_5', 'pee_pieub_6', 'pee_pieub_7', 'pee_pieub_8',
        'pee_lee_1', 'pee_lee_2',
        'ut_ieung_1', 'ut_ieung_2', 'ut_ieung_3', 'ut_ieung_4',
        'ut_eo_1', 'ut_eo_2', 'ut_eo_3', 'ut_eo_4',
        'ut_ssiot_1', 'ut_ssiot_2', 'ut_ssiot_3', 'ut_ssiot_4', 'ut_ssiot_5', 'ut_ssiot_6', 'ut_ssiot_7', 'ut_ssiot_8',
        'seub_siot_1', 'seub_siot_2', 'seub_siot_3', 'seub_siot_4',
        'seub_eu_1', 'seub_eu_2',
        'seub_bieub_1', 'seub_bieub_2', 'seub_bieub_3', 'seub_bieub_4', 'seub_bieub_5', 'seub_bieub_6', 'seub_bieub_7', 'seub_bieub_8', 
        'nee_nieun_1','nee_nieun_2', 'nee_nieun_3',
        'nee_lee_1', 'nee_lee_2',
        'da_digeut_1', 'da_digeut_2', 'da_digeut_3', 'da_digeut_4', 'da_digeut_5',
        'da_ah_1', 'da_ah_2', 'da_ah_3', 'da_ah_4']

print(len(names))